# Numpy Array

In [2]:
import numpy as np

x = np.array([1,2,3,4,5])

print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

%timeit np.arange(1,9)**4

4.39 µs ± 1.45 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
l = []

for i in range(1,5):
    
    int_1 = int(input("Enter : "))
    
    l.append(int_1)
    
    
print(np.array(l))    

Enter : 12
Enter : 13
Enter : 14
Enter : 15
[12 13 14 15]


# Dimension in Array

In [5]:
a = np.array([1,2,3,4])
print(a)
print(a.ndim)

[1 2 3 4]
1


In [6]:
ar2 = np.array([[1,2,3,4], [5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [7]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [8]:
ar3.shape

(1, 3, 4)

In [9]:
ar2.shape

(2, 4)

In [10]:
ar2.itemsize

4

In [11]:
ar3.itemsize

4

# NumPy Function

Array Filled with zeros
Array filled with ones
create an empty array
An array with range of elements
Array Diagonal elemnts filled with ones
create an array with special value that are spaced linearly

In [12]:
arr = np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [13]:
x = np.ones(4)
print(x)

[1. 1. 1. 1.]


In [14]:
emp = np.empty(4)
print(emp)

[1. 1. 1. 1.]


In [15]:
rang = np.arange(1,5)
print(rang)

[1 2 3 4]


In [16]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
idt = np.identity(3)
print(idt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
diag = np.eye(3)
print(diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
lp = np.linspace(1,10, num = 5)
print(lp)

[ 1.    3.25  5.5   7.75 10.  ]


# Random 

# Rand() value between 0 and 1

# Randn() value close to zero may be + or -

# Ranf () half interval value of 0 and 1



In [20]:
var = np.random.rand(4)

print(var)

[0.72539106 0.92389195 0.72005248 0.16224189]


In [21]:
var1 = np.random.rand(2,5)

print(var1)

[[0.28706516 0.97612404 0.95658182 0.47906978 0.39690022]
 [0.03469516 0.27718449 0.57158063 0.92060609 0.86760126]]


In [22]:
x = np.random.randn(4)

print(x)

[ 0.92938329 -0.75783385 -0.71045382 -1.29871129]


In [23]:
y = np.random.randn(1,5)

print(y)

[[-1.42171846 -1.20495077 -2.64131572 -1.10153798 -0.43545112]]


In [24]:
rand = np.random.ranf(4)

print(rand)

[0.21487571 0.10013267 0.47550935 0.87507662]


In [25]:
z = np.random.randint(5,20,5)

print(z)

[ 8 18 17 13 15]


# Data Types of NumpyArray

In [31]:
a = np.array([1,2,3,4,5], "f")
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float32


# astype used to change type of data type

In [33]:
a.astype(np.int64)

array([1, 2, 3, 4, 5], dtype=int64)

In [34]:
a.astype(np.float64)

array([1., 2., 3., 4., 5.])

# Array Operation

In [37]:
a1 = np.arange(12).reshape(3,4)

a2 = np.arange(12,24).reshape(3,4)


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
# Scalar Operation
#Arithematic
a1 * 2

a1&2

a1 + 2

a1 - 2

#Relational

a2 > 5

a2 < 20

a2 > 15

a2 >= 5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
# Vector Operation

#Arithimatic

a1 + a2

a1 * a2

a1 / a2

a1 - a2

#Relational

a1 > a2

a2 >= a1

a1 == a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# Array Function

In [62]:
x1 = np.random.random((3,3))
x1 = np.round(x1*100)

x1

array([[57., 87., 94.],
       [54., 42., 65.],
       [41., 38., 76.]])

In [64]:
#Max,Min,Sum,Product
np.max(x1)
np.min(x1)
np.sum(x1)
np.prod(x1)

np.max(x1, axis = 1) #axis function used to acces each max , sum , prod# or min element from existing row and column

np.min(x1, axis = 0)

array([41., 38., 65.])

In [68]:
#Mean,Median,std,var

#np.mean(x1)
#np.median(x1)
#np.std(x1)
#np.var(x1)

61.55555555555556

In [ ]:
#Trignomatric Function
#np.sin(x1)

In [72]:
#Dot Product
x2 = np.arange(12).reshape(3,4)
x3 = np.arange(12,24).reshape(4,3)

np.dot(x2,x3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [74]:
#Log,Exponent
#np.log(x1)
#np.exp(x1)

array([[5.68572000e+24, 6.07603023e+37, 6.66317622e+40],
       [2.83075330e+23, 1.73927494e+18, 1.69488924e+28],
       [6.39843494e+17, 3.18559318e+16, 1.01480039e+33]])

In [79]:
#Round
#floor return back value
#ceil return Front value
np.round(np.random.random((2,3))*100)

np.floor(np.random.random((1,4))*50)

np.ceil(np.random.random((2,4))*20)

array([[19., 20., 11., 16.],
       [11.,  2.,  2., 10.]])

# indexing

In [109]:
z = np.arange(12)
print(z)

z1 = np.arange(12,24).reshape(3,4)
print(z1)

z2 = np.arange(8).reshape(2,2,2)
print(z2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [118]:
#z[8]#1D

#z1[1,1]#2D

#z2[1,0,0]3D tenser


4

In [120]:
z2[1,1,0]

6

# Slicing

In [122]:
z[2:5]#1D

array([2, 3, 4])

In [123]:
z[2:5:2]#1D

array([2, 4])

In [126]:
#2D
z1[0,:]

array([12, 13, 14, 15])

In [129]:
z1[:,2]

array([14, 18, 22])

In [130]:
z1[1:, 1:3]

array([[17, 18],
       [21, 22]])

In [131]:
z1[::2,::3]

array([[12, 15],
       [20, 23]])

In [139]:
z1[::2, 1::2]

array([[13, 15],
       [21, 23]])

In [143]:
z1[1,::3]

array([16, 19])

In [146]:
z1[0:2,1:4]

array([[13, 14, 15],
       [17, 18, 19]])

In [147]:
y1 = np.arange(1).reshape(3,4)
y1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
z2 = np.arange(27).reshape(3,3,3)
z2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [150]:
z2[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [151]:
z2[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [153]:
z2[0,1,:]

array([3, 4, 5])

In [156]:
z2[1,:,1]

array([10, 13, 16])

In [161]:
z2[2,1:3,1:]

array([[22, 23],
       [25, 26]])

In [162]:
z2[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iterating in numpyArray

In [163]:
for i in z:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [164]:
for i in z1:
    print(z1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [165]:
for i in z2:
    print(z2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [166]:
for i in np.nditer(z2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [168]:
#Transpose
np.transpose(z1)

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [171]:
z1.T

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [173]:
z1.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# Stacking

In [174]:
#Horizontal stack
z3 = np.arange(12).reshape(3,4)
z4 = np.arange(12,24).reshape(3,4)

np.hstack((z3,z4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [175]:
#vertical stack
np.vstack((z3,z4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])